package broker

import "fmt"

var brokerNames = map[int64]string{
	1:   "Kumari Securities Private Limited",
	3:   "Arun Securities (PVT) Ltd.",
	4:   "Opal Securities Investment (PVT) Ltd.",
	5:   "Market Securities & Exchange (PVT) Ltd.",
	6:   "Agrawal Securities (PVT) Ltd.",
	7:   "J.F. Securites (PVT) Ltd.",
	8:   "Brilliant Securities Pvt. Ltd.",
	10:  "Pragyan Securities (PVT) Ltd.",
	11:  "Malla & Malla Stock Broking Company Pvt. Limited",
	13:  "Thrive Brokerage House Pvt. Ltd",
	14:  "Nepal Stock House (PVT) Ltd.",
	16:  "Primo Securities (PVT) Ltd.",
	17:  "ABC Securities Private Limited",
	18:  "Sagarmatha Securities Private Limited",
	19:  "Nepal Investment And Securities Trading Private Limited",
	20:  "Sipla Securities Private Limited",
	21:  "Midas Stock Broking Company Private Limited",
	22:  "Siprabi Securities Pvt. Ltd.",
	25:  "Sweta Securities Private Limited",
	26:  "Asian Securities Private Ltd.",
	28:  "Shree Krishna Securities Ltd.",
	29:  "Trisul Securities & Invt. Ltd.",
	32:  "Premier Securities Company Ltd.",
	33:  "Dakshinkali Investment & Securities Pvt. Ltd.",
	34:  "Vision Securities Pvt. Ltd",
	35:  "Kohinoor Investment & Securities Pvt. Ltd.",
	36:  "Secured Securities Ltd.",
	37:  "Swarna Laxmi Securities Pvt. Ltd.",
	38:  "Dipshikha Dhitopatra Karobar Co. Pvt Ltd.",
	39:  "Sumeru Securities Pvt. Ltd.",
	40:  "Creative Securities Pvt Ltd",
	41:  "Linch Stock Market Ltd.",
	42:  "Sani Securities Company Ltd.",
	43:  "South Asian Bulls Pvt. Ltd.",
	44:  "Dynamic Money Managers Securities Pvt. Ltd.",
	45:  "Imperial Securities Company Pvt. Ltd.",
	46:  "Kalika Securities Pvt. Ltd.",
	47:  "Neev Securities Pvt. Ltd.",
	48:  "Trishakti Securities Public Limited",
	49:  "Online Securities Pvt. Ltd.",
	50:  "Cristal Kanchanjanga Securites Pvt. Ltd.",
	51:  "Oxford Securities Pvt. Ltd.",
	52:  "Sundhara Securities Limited",
	53:  "Investment Management Nepal Pvt. Ltd.",
	54:  "Sewa Securities Pvt. Ltd.",
	55:  "Bhrikuti Stock Broking Co. Pvt. Ltd.",
	56:  "Sri Hari Securities Pvt. Ltd.",
	57:  "Aryatara Investment & Securities",
	58:  "Naasa Securities Co. Ltd.",
	59:  "Deevyaa Securities & Stock House Pvt. Ltd",
	60:  "Nagarik Stock Dealer",
	61:  "Bhole Ganesh Securities Ltd.",
	62:  "Capital Max Securities Ltd",
	63:  "Himalayan Brokerage Company Limited",
	64:  "Sun Securities Pvt. Ltd.",
	65:  "Sharepro Securities Private Limited",
	66:  "Miyo Securities Pvt Ltd",
	67:  "Property Wizard Limited",
	68:  "Elite Stock House Limited",
	69:  "Index Securities Limited",
	70:  "Infinity Securities Limited",
	71:  "Shubhakamana Securities Pvt. Ltd.",
	72:  "Hatemalo Financial Services Private Limited",
	73:  "Money World Share Exchange PVT Ltd",
	74:  "Kalash Stock Market Pvt. Ltd.",
	75:  "N.I.M.B. Stock Markets Limited",
	76:  "Machhapuchchhre Securities Limited",
	77:  "Nabil Stock Dealer Ltd.",
	78:  "Garima Securities Limited",
	79:  "Pahiinvestment",
	80:  "Indira Securities Pvt. Ltd.",
	81:  "Aakashbhairab Securities Ltd.",
	82:  "N.M.B. Securities Limited",
	83:  "Sanima Securities Limited",
	84:  "Milky Way Share Broker Company Ltd.",
	85:  "Capital Hub Pvt. Ltd.",
	86:  "Stoxkarts Securities Limited",
	87:  "S.P.S.A. Securities Limited",
	88:  "Blue Chip Securities Ltd.",
	89:  "Global IME Securities Limited",
	90:  "Sajilo Broker Limited",
	91:  "Citizens Share Broker Limited",
	92:  "Roadshow Securities Limited",
	93:  "Beni Securities Pvt. Ltd.",
	94:  "K.B.L. Securities Limited",
	95:  "Magnet Securities and Investment Company Private Limited",
	96:  "Himalayan Securities Limited",
	97:  "R.B.B. Securities Company Ltd",
	98:  "Trademow Securities Private Limited",
	99:  "Prabhu Stock Market Limited",
	100: "Sunrise Securities Limited",
	101: "Apple Securities Private Limited",
}

func BrokerName(id int64) string {
	if name, ok := brokerNames[id]; ok {
		return name
	}
	return fmt.Sprintf("Broker %d", id)
}

func BrokerLabel(id int64) string {
	return fmt.Sprintf("%d:%s", id, BrokerName(id))
}